security:

  encoders:
    App\Entity\User:
      algorithm: bcrypt
      cost: 13

  role_hierarchy:
    ROLE_USER: ROLE_USER
    ROLE_ADMIN: ROLE_USER

  providers:
    jwt_user_provider:
      id: App\Providers\JwtUserProvider

  firewalls:
    jwt:
      pattern: ^/api
      stateless: true
      simple_preauth:
        authenticator: App\Auth\JwtAuthenticatorServer
      provider: jwt_user_provider