general:
  path: /
  methods: [GET]
  controller: App\Controller\GeneralController::index

getToken:
  path: /getToken
  methods: [POST]
  controller: App\Controller\LoginController::getToken

refreshTokens:
  path: /refresh-tokens
  methods: [POST]
  controller: App\Controller\TokenController::refreshTokens

disableTokens:
  path: /disable-tokens
  methods: [POST]
  controller: App\Controller\TokenController::disableTokens