imports:
    - { resource: services/* }

parameters:
    jwt_timelife: '+1 hour'
    jwt_refresh_timelife: '+60 days'
    jwt_algorithm: 'RS256'
    jwt_private_key: '%kernel.project_dir%/rsa_256.pem'
    jwt_public_key: '%kernel.project_dir%/rsa_256.pub'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Command,Controller,Repository,Auth,Migrations,Service,Helpers,Kernel.php}'